/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lXImBr834Hx
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardContent } from "@/components/ui/card";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { JSX, SVGProps } from "react";
import { Textarea } from "@/components/ui/textarea";

export default function profileComponent() {
  return (
    <div className="flex flex-col items-center justify-center min-h-dvh rounded-xl">
      <Card className="w-full max-w-3xl rounded-xl">
        <CardHeader className="bg-muted/20 p-6 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Avatar className="h-16 w-16">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>SG</AvatarFallback>
            </Avatar>
            <div className="grid gap-1">
              <div className="text-xl font-bold">Sundar</div>
              <div className="text-sm text-muted-foreground">
                example@google.com
              </div>
            </div>
          </div>
          <div className="flex gap-2">
            <Button variant="outline">
              <LogInIcon className="mr-2 h-4 w-4 " />
              Enterprise Login
            </Button>
            <Button>
              <UserIcon className="mr-2 h-4 w-4" />
              User Login
            </Button>
          </div>
        </CardHeader>
        <CardContent className="p-6 grid gap-6">
          <div className="grid gap-2">
            <div className="text-lg font-semibold">About Sundar</div>
            <p className="text-muted-foreground">
              {/* Sundar is a software engineer with a strong interest in networks
              and AI. He is passionate about building innovative solutions that
              push the boundaries of technology. */}
              <div className="w-full flex flex-col">
                <Textarea />
                <button className="min-w-20 h-10 border-2 rounded-xl">
                  submit
                </button>
                {/* comment input and button */}
              </div>
            </p>
          </div>
          <Separator />
          <div className="grid gap-2">
            <div className="text-lg font-semibold">About the Company</div>
            <p className="text-muted-foreground">
              {/* Our company is a leading provider of enterprise-grade software
              solutions. We specialize in developing cutting-edge technologies
              that empower our clients to achieve their business goals. Our team
              of experts is dedicated to delivering exceptional service and
              driving innovation in the industry. */}
              <div className="w-full flex flex-col">
                <Textarea />
                <button className="min-w-20 h-10 border-2 rounded-xl">
                  submit
                </button>
                {/* comment input and button */}
              </div>
            </p>
          </div>
          <Separator />
          <div className="grid gap-2">
            <div className="text-lg font-semibold">Key Facts</div>
            <div className="grid grid-cols-2 gap-4 text-muted-foreground">
              <div>
                <span className="font-medium">Role:</span> Software Engineer
              </div>
              <div>
                <span className="font-medium">Interests:</span> Networks, AI
              </div>
              <div>
                <span className="font-medium">Joined:</span> June 2018
              </div>
              <div>
                <span className="font-medium">Location:</span> Mountain View, CA
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function LogInIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>
  );
}

function UserIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}

function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
